### ISSUE TITLE
Temporal values seem to be unnecessarily offsetted

### ISSUE THREAD

**Issue by bissaias** [vert-x3/vertx-jdbc-client#20]
I am inserting and then selecting a ``datetime`` field from MySql. While the code executes successfully, the date value retrieved from the ``ResultSet`` is offsetted by 3h. For example while the date inserted was ``2015-06-26 22:25:54.0`` the retrieved date was ``2015-06-26T19:25:54Z``. After some investigation I discovered the following code in ``io.vertx.ext.jdbc.impl.actions.AbstractJDBCStatement`` which creates the problem:
```
    // temporal values
    if (value instanceof Date || value instanceof Time || value instanceof Timestamp) {
      return OffsetDateTime.ofInstant(Instant.ofEpochMilli(((java.util.Date) value).getTime()), ZoneOffset.UTC).format(ISO_OFFSET_DATE_TIME);
    }
```
I admit that I am not familiar with the date api of JDK 8 but this code looks highly unnecessary to me.

**Comment by timyates** [comment]
So, to convert the date from the database into a format that can be added
to a Json object, it is converting it to an ISO date string in the UTC
timezone:

https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

My guess is that you aren't in the UTC timezone?

You should be able to convert the date field to a String format in the
database, in your select statement

Or convert this into a DateTime local to your timezone after receiving the
json

Tim

**Comment by bissaias** [comment]
Thanks for the info Tim. However I still don't get why you don't return a string representation of the date value as is (i.e. as it's returned by the jdbc driver) and let the developer do the rest, since most of the times developers would want to process dates in the local time zone. After all this is the vertx-jdbc module and I would expect that it resembles standard jdbc functionality.
If fore some reason you still think it's necessary to convert the date in UTC timezone, please state that in the documentation and provide also a code fragment of how to roll it back to the local timezone.

**Comment by pmlopes** [comment]
The reason for doing this is because with vertx or any distributed application you have no control or knowledge at front about the timezone of the other nodes. Say that your application is composed of 2 verticles and these 2 verticles are deployed one in Europe and other in Asia, if you pass temporal values across verticles say for example: Jan 1st 2015 9:00 AM what does that mean? is it the time in Europe? is it the time in Asia? which TZ from Europe is it? which TZ from Asia is it?

So by convention all temporals are encoded as UTC, exactly as MongoDB does, exactly as all web browsers do when they encode Date to JSON. see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

Now the format used is a standard so you can use several ways, if you're in javascript you just do `new Date(string)` if you're in Java it depends on your taste: `OffsetDateTime.parse(string)` is by far the shortest or: `DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");df.setTimeZone(TimeZone.getTimeZone("UTC")); df.parse(str)`

**Comment by timyates** [comment]
This came in to align it with the mongo client according to the pull
request:

https://github.com/vert-x3/vertx-jdbc-client/pull/18

**Comment by pmlopes** [comment]
In order to solve this kind of questions there is a proposal on the wiki for a update to the JsonAPI:

https://github.com/vert-x3/wiki/wiki/Update-JSON-API

Basically it means that we should have full ECMA-404 implementation (JSON Spec)  + RFC7493 (Interop JSON) which means adding methods to encode/decode binary streams to Base64 (already present) + methods to encode/decode Temporal values to ISODate format as per the link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

**Comment by bissaias** [comment]
I totally get it now, thanks for the update. In the end I managed to convert the UTC time to local time using
```
public static String toLocalDTString(String utc) {
   return OffsetDateTime.parse(utc).atZoneSameInstant(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_DATE_TIME);
}
```
My feeling is that there should be some convenience methods present in the JsonAPI for this kind of things since most of the times the developer would like to have the local date from the JsonObject, e.g.:
```
public String getUTCtoLocalDateTimeString(String key) {
  //convertion code
}

```

**Comment by pmlopes** [comment]
Yes i agree, that is why i open that wiki page to propose an API update.

**Comment by YheCoder** [comment]
Has this proposal ever been addressed? I ran into this issue and would be great if there is a way to get the date as string as is without converting it to utc.

https://github.com/vert-x3/wiki/wiki/Update-JSON-API
