### ISSUE TITLE
JDBC call - executeBlocking with ordered=true

### ISSUE THREAD

**Issue by leosilvadev** [vert-x3/vertx-jdbc-client#84]
### Version

* vert.x core: 3.2.1
* vert.x jdbc-client: 3.2.1
* jdbc driver: mysql-connector-java 5.1.39
* RDBMS: Mysql

### General info

* What is your jdbc driver
* What is your RDBMS server
* What is your connection string (no user/passwords please!)

### Context
Not a bug probably, but a question: why the jdbc calls are executed with executeBlocking in ordered way?
I was making some load tests in one of our api and at some point we were using a lot of connections (80) to deal with 500 requests p/second, after that with 1k requests even increasing the number of connections in database (rds) we could not use more, after investigate a bit I realized that the jdbc call were being executed at the same thread, because jdbc call are executed in ordered way.

**Comment by tsegismont** [comment]
You can use issues to ask implementation questions though the preferred way
would be to drop an email to the vertx-dev list (see "Developer Group" on
http://vertx.io/community/)

That said, jdbc calls are executed with executeBlocking set to true because
all actions on a JDBC connection must happen in order. It is not a global
serialization mechanism though, an internal WorkerExecutor is created for
each connection object on top the worker pool.

2017-01-01 17:37 GMT+01:00 Leonardo Silva <notifications@github.com>:
