### ISSUE TITLE
JDBCSQLRowStream.readRows() should fail fast if ResultSet is closed

### ISSUE THREAD

**Issue by dgbustos** [vert-x3/vertx-jdbc-client#97]
### Version

* vert.x core: 3.4.1
* vert.x jdbc-client: 3.4.1
* jdbc driver: c3p0-0.9.5.2 & mysql-connector-java-5.1.38
* RDBMS: MariaDB 10.0.29

### General info

* What is your jdbc driver

c3p0 & mysql-connector-java

* What is your RDBMS server

MariaDB

* What is your connection string (no user/passwords please!)

jdbc:mysql://localhost/test_branddb

### Context

I was trying out the streaming API after upgrading to Vert.x 3.4.  The exception handler was being called with an exception saying the result set had been closed.  I realized that my utility method closes the connection before invoking the callback.  To make this less confusing, `JDBCSQLRowStream.readRows()` could check whether the `ResultSet` is closed and fail faster with an informative error message.

**Comment by pmlopes** [comment]
If you close the connection, calling the code:

```java
if (rs.isClosed()) {
   throw new SQLException("ResultSet is closed.");
}
```

Will not trigger the the exception because the state of the result set is not linked to the state of the connection, or it can have different behaviour if you use different connection pools.

You do get the error on the exception handler that the state of the cursor is not valid. But again once you swap connection pools the message can be different too.
